# Site
name: 'RetraiteActive'
description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/avatar.png'
baseurl: 'cogsea.github.io/23724173.github.io'
# disqus: ''
# email: ''
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    marianne:
      name: Marianne L.
      # site:    
      avatar: /assets/images/avatar.png
      bio: "Bonjour, je m'appelle Marianne. Je suis jeune retraitée et éditrice de RetraiteActive."
      # email:          
      # twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: marianne
      avatar: /assets/images/avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]